[package]
name = "markovian_core"
version = "0.1.0"
authors = ["Michael Anderson <drmikeando@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.4"
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
snafu = "0.7.2"
